# Generated by Django 3.0.2 on 2020-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messier_number', models.CharField(max_length=100)),
                ('usual_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ngc', models.CharField(max_length=100)),
                ('constellation', models.CharField(max_length=100)),
                ('messier_type', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('distance_value', models.FloatField()),
                ('distance_unit', models.CharField(max_length=100)),
                ('magnitude', models.FloatField()),
                ('ascension', models.CharField(max_length=100)),
                ('discovery_date', models.DateField()),
                ('discoverer', models.CharField(max_length=100)),
                ('image_link', models.TextField()),
            ],
            options={
                'ordering': ['messier_number'],
            },
        ),
    ]
