# Generated by Django 3.0.2 on 2020-02-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobject',
            options={'ordering': ('messier_number',)},
        ),
        migrations.RemoveField(
            model_name='mobject',
            name='highlighted',
        ),
    ]
